### ISSUE TITLE
create package for Centos 7

### ISSUE THREAD

**Issue by mkudlej** [Tendrl/ceph_integration#10]
For CI and integration testing it is important to install all Tendrl components from packages.

**Comment by ktdreyer** [comment]
Martin, does the package at https://copr.fedorainfracloud.org/coprs/tendrl/tendrl/ install properly now?

**Comment by r0h4n** [comment]
Fixed: https://github.com/Tendrl/ceph_integration/blob/master/tendrl-ceph-integration.spec

Can re-open if issue still exists
