### ISSUE TITLE
etc directory is incompatible with documentation

### ISSUE THREAD

**Issue by fbalak** [Tendrl/ceph_integration#100]
According to installation documentation [1] some configuration files from ceph-integration etc directory should be copied to specific directories but etc directory structure is different from what is specified in documentation.
According to documentation logging.yaml.timedrotation.sample should be located at etc/samples/logging.yaml.timedrotation.sample but it is located at etc/tendrl/ceph-integration/logging.yaml.timedrotation.sample.
According to documentation there should be etc/tendrl/tendrl.conf.sample but there is no such file.
Documentation and etc directory should be united.

[1] https://github.com/Tendrl/ceph-integration/blob/efe8a549557023cc95bb188344918451c0707a16/doc/source/installation.rst

**Comment by brainfunked** [comment]
The documentation applies to source based installations. The RPM packages take care of the configuration files copying.

**Comment by sankarshanmukhopadhyay** [comment]
@brainfunked perhaps we add a cover-all note on the documentation that this is applicable to the source-based installations. Packages available via packaging routines of distributions would be using manifest files to take care of this by default.

This issue should be re-opened if the topic exists in the packages.
