### ISSUE TITLE
daemon fails because cluster has different name than 'ceph'

### ISSUE THREAD

**Issue by mkudlej** [Tendrl/ceph_integration#112]
It seems that ceph integration daemon work only if there is cluster with name *ceph*. It should work also if node is part of cluster with different name than *ceph*.
Example of call which breaks daemon:
```
$ python /usr/bin/ceph version -f json
Error initializing cluster client: Error('error calling conf_read_file: error code 22',)
```
which is part of start of daemon
```
systemctl start tendrl-cephd.service
```

**Comment by mkudlej** [comment]
This problem is worst than I expected. Command:
```
python /usr/bin/ceph version -f json
```
cannot be run on OSD nodes because they are not Ceph clients by default. So I think ```ceph``` command should be substitute by something else.
--> moving this issue to blockers

**Comment by shtripat** [comment]
Sent https://github.com/Tendrl/ceph-integration/pull/118 to fix this.
We rather should be using `ceph --version` command which works on both mon and ceph nodes properly.

**Comment by sankarshanmukhopadhyay** [comment]
@shtripat is this fix planned to be available in the latest build?

**Comment by cybernth** [comment]
@sankarshanmukhopadhyay This was merged yesterday, so should be available in the last nightly build(1.2-02_21_2017_06_35_02 )

**Comment by sankarshanmukhopadhyay** [comment]
ACK. Thank you @nthomas-redhat Subsequent to testing, if found fixed, I'd request the reporter to mark this as closed. And similarly for other issues which have been resolved in the latest builds.

**Comment by sankarshanmukhopadhyay** [comment]
@mkudlej - once you commence testing, please verify if the fix works and we can resolve this issue.

**Comment by mkudlej** [comment]
With today packages I see properly stored ceph cluster in *Etcd*. Once I can confirm this by importing cluster with different name than *ceph*, I'll close this issue. This is blocked by https://github.com/Tendrl/api/issues/82

**Comment by sankarshanmukhopadhyay** [comment]
Since https://github.com/Tendrl/api/issues/82 seems to have been addressed, can we attempt to confirm the fix this week?

**Comment by mkudlej** [comment]
There is new blocker https://github.com/Tendrl/performance-monitoring/issues/58 which blocks also this.

**Comment by sankarshanmukhopadhyay** [comment]
The fix for https://github.com/Tendrl/performance-monitoring/issues/58 has been merged. Please check the latest builds when available and update this issue.

**Comment by mkudlej** [comment]
I don't see this issue with:
- api server: 
```
tendrl-api-1.2.1-03_01_2017_01_51_02.noarch
tendrl-api-doc-1.2.1-03_01_2017_01_51_02.noarch
tendrl-api-httpd-1.2.1-03_01_2017_01_51_02.noarch
tendrl-dashboard-1.2.1-03_01_2017_13_39_11.noarch
```
- ceph node:
```
centos-release-ceph-jewel-1.0-1.el7.centos.noarch
ceph-base-10.2.3-0.el7.x86_64
ceph-common-10.2.3-0.el7.x86_64
ceph-mon-10.2.3-0.el7.x86_64
ceph-selinux-10.2.3-0.el7.x86_64
libcephfs1-10.2.3-0.el7.x86_64
python-cephfs-10.2.3-0.el7.x86_64
tendrl-ceph-integration-1.2.1-03_01_2017_06_35_02.noarch
tendrl-commons-1.2.1-2.el7.centos.noarch
tendrl-node-agent-1.2.1-03_01_2017_00_47_35.noarch
tendrl-performance-monitoring-1.2.1-03_01_2017_03_02_02.noarch
```
--> CLOSE
