### ISSUE TITLE
Delete Pool & Delete RBD

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ceph_integration#135]
@brainfunked 

**JIRA References:**
- [Delete Ceph Pool in UI](https://tendrl.atlassian.net/browse/TEN-226)
- [Delete Ceph RBD in UI](https://tendrl.atlassian.net/browse/TEN-227)

A couple concerns raised by @cloudbehl about the lack of API's for some of the validations needed prior to proceeding with deletion of pool / RBD.  They include:
- How to find out the clients for the pool / RBD? If we cannot get this information, then we'll provide sufficient warning message about the user needing to take care of it.
- No support for snapshots and clones at the moment.  If we cannot get this information for now, then we'll provide sufficient warning message about the user needing to take care of it.
- How to know if RBD is mapped?  There's no API for this, but using the CLI you can find this out.  See https://ceph.com/geen-categorie/ceph-find-whos-mapping-a-rbd-device/ for more information.
- How to know if RBD is locked?  Once again, you can use the CLI to see this information.  Refer to http://docs.ceph.com/docs/master/man/8/rbd/ for further information.

**Comment by gnehapk** [comment]
@julienlim @mcarrano Can you please provide us the warning messages for all the above cases.

**Comment by nthomas-redhat** [comment]
This capability will be scoped after April.
@sankarshanmukhopadhyay could you please add appropriate labels to this issue?

**Comment by sankarshanmukhopadhyay** [comment]
@r0h4n @nthomas-redhat - aside from the technical aspect of having to fall back to CLI for the mapping and locking information - are there any specific performance or, data consistency challenges which the lack of available API will result in?

It would seem that the clients for the pool and the snapshot/cloning operation support need to be handled by providing suitably clear warnings to the user.

**Comment by brainfunked** [comment]
If we're allowing an operation that has a cascading effect on other objects, each object affected needs to be explicitly listed before the administrator continues with the operation.

**Comment by cybernth** [comment]
Per UX design( https://redhat.invisionapp.com/share/Z9AE9W6H4#/screens/219673762 and  https://redhat.invisionapp.com/share/THAEA6CEA#/screens/219673484), a list of pre-checks needs to be done before pool/rbd deletion. Below list is the what is possible at the moment:

**Delete Pool**
Can be done:
- check if nodelete flag is set -- _Yes_
- Check if there are any RBDs -- _yes_
- Check if there are any snapshots --_yes_
- Check if there are any objects in the pool -- _yes_
Differ:
- if you created users with permissions strictly for a pool you created, you should consider deleting those users too -- _ceph user management is not supported currently. Will relook at this when this feature is available_
- If you created your own rulesets and rules for a pool you created , you should consider removing them when you no longer need your pool. -- _I am not seeing any such scenario currently. Will look at this later_
Not sure how :
-if a pool is used for openstack, openstack client configuration changes would be required -- How tendrl know that a particular pool is used by openstack? -- _System needs to verify there are no clients accessing the pool --Is there a way to find out the no of clients connected to a pool?_

**Delete RBD**
Can be done :
- check if there any snapshots or clones -- _yes_
-  Check if there is data in rbd --_yes_
- if there is any clients accessing RBD --_yes_
- Check RBD is mapped --_yes_
- Check RBD is locked --_yes_
Differ:
-if you created users with permissions strictly for a rbd you created, you should consider deleting those users too -- _ceph user management is not supported currently. Will relook at this when this feature is available_

@brainfunked @julienlim please provide your input on items listed under 'Differ' and 'Not sure how'

**Comment by julienlim** [comment]
@nthomas-redhat  Regarding the "Differ" and "Not sure how" items, they are merely text warning messages and don't require any querying as I realize that will be tough to do.  These are best practices and/or recommendations from upstream for deletion of pools and RBDs.

**Comment by julienlim** [comment]
@gnehapk The warning messages should be in the designs.  Is there a specific scenario unaccounted for?

**Comment by r0h4n** [comment]
@nthomas-redhat  @gnehapk @julienlim is this one done?
