### ISSUE TITLE
too many temporary ansible files

### ISSUE THREAD

**Issue by mkudlej** [Tendrl/ceph_integration#143]
There are too many temporary ansible files in tendrl dir tree.
```
$ ls  /var/lib/tendrl/.ansible/tmp | wc -l
34746
$ du -hc /var/lib/tendrl/.ansible/tmp
...
176K	/var/lib/tendrl/.ansible/tmp/ansible-local-886365Mk9CfL
176K	/var/lib/tendrl/.ansible/tmp/ansible-local-886477tsroIM/ansiballz_cache
176K	/var/lib/tendrl/.ansible/tmp/ansible-local-886477tsroIM
176K	/var/lib/tendrl/.ansible/tmp/ansible-local-886625q5XcOt/ansiballz_cache
176K	/var/lib/tendrl/.ansible/tmp/ansible-local-886625q5XcOt
176K	/var/lib/tendrl/.ansible/tmp/ansible-local-886773HobMxi/ansiballz_cache
176K	/var/lib/tendrl/.ansible/tmp/ansible-local-886773HobMxi
5.9G	/var/lib/tendrl/.ansible/tmp
5.9G	total
```
It seems to me that they are not used and also not removed after they are used.

Reproducer:
Install cluster with ceph integration and leave it for couple of days.

**Comment by sankarshanmukhopadhyay** [comment]
Could you please provide more detail as to how this is blocking the tests? The files do need to be cleaned up and the fix has to be put in.

**Comment by shtripat** [comment]
@sankarshanmukhopadhyay problem what happens is that if we leave ceph-integration running for quite sometime like 20hrs+ the no of open fds reaches 1020+ and any call for pool/rbd creation fails saying too many open files.

**Comment by mkudlej** [comment]
@sankarshanmukhopadhyay it consumes all disk capacity on ceph osd nodes. Yes, there is workaround.

**Comment by r0h4n** [comment]
Fixed: https://github.com/Tendrl/commons/commit/2bd00bf584b650d07b1154ac766e99bb7c4a2c39#diff-52a44eabbad36a1b132c91c25e587e1b  (branch:develop)

Apologies, the way we generate ansible executable modules should have been fixed long back.

**Comment by sankarshanmukhopadhyay** [comment]
Do we not have a build for this yet?

**Comment by mkudlej** [comment]
@sankarshanmukhopadhyay I don't know if there is build. It was merged to devel branch.

@r0h4n How do I know that this change is already in master -> packages?

**Comment by sankarshanmukhopadhyay** [comment]
@mkudlej this will be definitely part of the next tagged build. the commit ID is provided above by Rohan

**Comment by r0h4n** [comment]
@mkudlej We make builds of master and develop branch for every commit and the builds are tagged by timestamp.

**Comment by mkudlej** [comment]
This seems to be solved.

**Comment by mkudlej** [comment]
Tested with 
```
tendrl-commons-1.2.1-03_24_2017_06_33_41.noarch
tendrl-node-monitoring-1.2.1-03_24_2017_01_12_05.noarch
tendrl-node-agent-1.2.1-03_24_2017_06_38_20.noarch
```
and it's OK.
