### ISSUE TITLE
PEP8 check fails

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/ceph_integration#145]
[PEP8 code style](https://www.python.org/dev/peps/pep-0008/) is not followed which makes `pep8` check fail during unit test execution, see [latest report from Travis CI](https://travis-ci.org/Tendrl/ceph-integration/jobs/208218651), which has about 4500 lines.

Note: to run pep8 check yourself locally, run `tox -e pep8` in current master branch, the environment and the check would be the same as run by Travis CI.

**Comment by rishubhjain** [comment]
@r0h4n 
Hi, I had started with the task, I guess its done , https://travis-ci.org/Tendrl/ceph-integration/jobs/234414387
Please check and provide me a feedback if possible

**Comment by r0h4n** [comment]
on latest commit develop branch, we still need some PEP8 fixes, please go ahead and fix them @rishubhjain , and we can then close this issue

**Comment by rishubhjain** [comment]
Completed PEP8 fixes : https://github.com/Tendrl/ceph-integration/pull/279
https://travis-ci.org/Tendrl/ceph-integration/jobs/242678281

**Comment by rishubhjain** [comment]
@r0h4n Should we close this issue?
