### ISSUE TITLE
rbd syncing throws exception if some protected rbds are there without provisioned size

### ISSUE THREAD

**Issue by shtripat** [Tendrl/ceph_integration#172]
Recently while doing rnd with protected rbds having some clients connected, found that field `provisioned_size` is not available. Due to this, the rbd syncing throws exception.

Need to correct, so it does not fail and still syncs the rbds, with empty value for `provisioned_size`.

**Comment by GowthamShanmugam** [comment]
@shtripat @anmolsachan  unable to reproduce this issue
