### ISSUE TITLE
After the cluster import  cluster_tendrl_context fields are not populated correctly

### ISSUE THREAD

**Issue by GowthamShanmugam** [Tendrl/ceph_integration#176]
After creating cluster, cluster_tendrl_context details  in /clusters/<cluster_id>/TendrlContext  are not getting populated correctly, except integration_id all other fields are empty. If we restart node-agent then all fields are getting populated.

**Comment by GowthamShanmugam** [comment]
@shtripat @r0h4n @nnDarshan i have raise error here because as per our discussion fix PR is for ceph-integration only.

**Comment by r0h4n** [comment]
Fixed: https://github.com/Tendrl/node-agent/blob/develop/tendrl/node_agent/node_sync/__init__.py

The PRs on ceph-integration and gluster-integration are not required, they shouldnt be handling tendrl_context the node-agent should do that
