### ISSUE TITLE
Create RBD task should fail if cluster is in "HEALTH_ERR" state

### ISSUE THREAD

**Issue by gnehapk** [Tendrl/ceph_integration#202]

**Comment by gnehapk** [comment]
@shtripat @r0h4n Please check.

**Comment by GowthamShanmugam** [comment]
This is problem fixed in PR https://github.com/Tendrl/ceph-integration/pull/206/files#diff-78effc7406fac248c720231d3287fdbbR620

**Comment by cybernth** [comment]
@GowthamShanmugam, Are you getting proper response from ceph cluster if the cluster in "HEALTH_ERR"  ?

**Comment by GowthamShanmugam** [comment]
@nthomas-redhat no, ceph is not returning anything, it just taking the request and waiting, the timeout code in tendrl is terminating the process and sending timeout response to the crud operation. It will update timeout job update and flow failed job update in in etcd.

**Comment by r0h4n** [comment]
@GowthamShanmugam This PR https://github.com/Tendrl/ceph-integration/issues/206 fixes the current issue right?

**Comment by GowthamShanmugam** [comment]
@r0h4n yes rohan it will fix this issue

**Comment by GowthamShanmugam** [comment]
@r0h4n i have verified this

{"publisher": "ceph_integration", "job_id": "c4803bcf-b74d-46d5-aca5-16d46b1b8de7", "timestamp": "2017-05-02T11:23:57.641947+00:00", "caller": {"function": "run", "line_no": 51, "filename": "/usr/lib/python2.7/site-packages/tendrl/ceph_integration/objects/rbd/atoms/create/__init__.py"}, "payload": {"message": "Failed to create rbd mmrbd3. Error: rbd command timed out"}, "priority": "info", "parent_id": null, "node_id": "82a58870-f30e-4459-a149-7cd08340a4ae", "cluster_id": "89604c6b-2eff-4221-96b4-e41319240240", "flow_id": "9bc41d8f-a0cf-420a-b2fe-18761e07f3d2", "message_id": "a83c9fb7-b6a0-480f-8514-955c4f31d8b6"}

**Comment by GowthamShanmugam** [comment]
@r0h4n we can close this issue
