### ISSUE TITLE
user requests just get submitted in ceph-integration

### ISSUE THREAD

**Issue by shtripat** [Tendrl/ceph_integration#203]
There is no tracking of user request once they are submitted to ceph cluster. The command might have failed behind the scene, but upper layers never come to know about the same.

This happens due to below piece of code in `manager/user_request.py` I feel

```
    def submit(self):
        assert self.state == self.NEW
        self._submit()
        self.state = self.SUBMITTED
```
Here the output of `self._submit()` is not considered is one thing, also there is no return value at all but the caller code under `sds_sync/__init__.py` receives a return value (which would effectively be `None` in all cases).

Ideally the request id which created should be tracked and once if complete, then only the task should be marked as successful.

**Comment by shtripat** [comment]
Some kind of maintenance of all the submitted requests and their current status may help here.

**Comment by r0h4n** [comment]
Closing this one @shtripat
