### ISSUE TITLE
Ceph response is not return to the crude operations correctly

### ISSUE THREAD

**Issue by GowthamShanmugam** [Tendrl/ceph_integration#213]
Here https://github.com/Tendrl/ceph-integration/blob/develop/tendrl/ceph_integration/objects/rbd/atoms/create/__init__.py#L34
we calling crud operation, problem is it always receive response like None, Because response is not return from user_request.py.
from https://github.com/Tendrl/ceph-integration/blob/develop/tendrl/ceph_integration/manager/user_request.py#L161 here we have to pass the repose.

Because this problem i faced some issue like, 
   i have checked rbd  creation when cluster is in Error state,  Job is completed successfully but rbd is not created. ceph.ceph_command() is giving error like  {'status': 1, 'err': 'rbd command timed out', 'out': ''} to submit function but submit function not returning the response to the crude operation.

we have to change if condition check also https://github.com/Tendrl/ceph-integration/blob/develop/tendrl/ceph_integration/objects/rbd/atoms/create/__init__.py#L36

because this response contain's no keyword error here the key is err

**Comment by GowthamShanmugam** [comment]
@shtripat @r0h4n @nthomas-redhat @gnehapk @nthomas-redhat

**Comment by GowthamShanmugam** [comment]
#202

**Comment by shtripat** [comment]
@GowthamShanmugam Does https://github.com/Tendrl/ceph-integration/pull/206 take care of this?

**Comment by GowthamShanmugam** [comment]
@shtripat, Yes that will fix this issue, one more thing is when timeout happens ceph gives response like
 {'status': 1, 'err': 'rbd command timed out', 'out': ''}

but in  tendrl/ceph_integration/manager/crud.py  you have checked if condition like request.state == "complete" and not request.error so this error will skip, so this problem will come again

**Comment by shtripat** [comment]
@GowthamShanmugam thanks for figuring this out and verifying the changes.
Have updated the PR with required changes to consider the response error status to mark the request properly.

**Comment by GowthamShanmugam** [comment]
The exact problem is we are not changing error is True for any response when it is fails, so it giving success for all the jobs. https://github.com/Tendrl/ceph-integration/pull/206/files#diff-78effc7406fac248c720231d3287fdbbR620 ( @shtripat patch) this will solbve this problem.

**Comment by r0h4n** [comment]
@GowthamShanmugam closing this one
