### ISSUE TITLE
RBD creation not supporting new pool creation if required.

### ISSUE THREAD

**Issue by anmolsachan** [Tendrl/ceph_integration#215]
As mentioned in this issue( https://github.com/Tendrl/dashboard/issues/266 ) the Dashboard has a flow for RBD creation where a user can select RBD creation on a new pool or existing pool. Currently in Back-End RBD creation requires pool_id as a mandatory parameter for RBD creation and Pool creation is a separate flow. Back-end should support pool creation for RBD creation under a single flow if required.

**Comment by cybernth** [comment]
https://github.com/Tendrl/api/issues/153

**Comment by cybernth** [comment]
https://github.com/Tendrl/dashboard/issues/266

**Comment by r0h4n** [comment]
Are you working on this?

**Comment by anmolsachan** [comment]
Yes I am. @r0h4n
