### ISSUE TITLE
Handle out of band deletes

### ISSUE THREAD

**Issue by cybernth** [Tendrl/ceph_integration#244]
Out of band deletes are not handled in ceph-integration
Tendrl has capabililty. any object (like OSD or pool) that wants to detect out of band deletes will need to add a TTL to its save()

**Comment by GowthamShanmugam** [comment]
@r0h4n if no changes in object here we are not updating pool detail of other details in etcd, so save method ttl is never work, i need your suggestion for this
@shtripat  comment also
