### ISSUE TITLE
Rbd creation sometimes fails due to rbd command timed out

### ISSUE THREAD

**Issue by anmolsachan** [Tendrl/ceph_integration#253]
Rbd creation sometimes fails due to following error:

> Error: rbd command timed out

**Comment by shtripat** [comment]
Any rbd request gets timed out if cluster is in error state.

**Comment by anmolsachan** [comment]
In my setup the cluster was in warning state and rbd creation failed once due to time out. After trying again the rbd got created.

**Comment by cybernth** [comment]
Once you create the cluster and try to create rbd, it fails consistently. After that I created a rbd using ceph cli and synced that into tendrl. After that rbd creation started working as expected. @shtripat This needs to be looked at on priority
