### ISSUE TITLE
Rename Pool remains in processing state.

### ISSUE THREAD

**Issue by cloudbehl** [Tendrl/ceph_integration#257]
Parameters Passed:
```
{
Pool.pool_id:2
Pool.poolname:"MyPool1"
}
```
RPM's used:
tendrl-node-agent-1.3.0-06_01_2017_05_05_04.noarch
tendrl-commons-1.3.0-06_01_2017_18_55_12.noarch
tendrl-api-1.3.0-06_01_2017_11_28_11.noarch

**Comment by r0h4n** [comment]
Please file bug as per https://github.com/Tendrl/documentation/wiki/Information-required-for-debugging-issues-on-the-Tendrl-stack

**Comment by cloudbehl** [comment]
@r0h4n Closing this Issue as the problem is solved. The endpoint UI was hitting was wrong and it was not documented properly in api. So will file an issue on API.
Will remember to file the bug as per the documentation from next time. Thanks
