### ISSUE TITLE
Pool/cluster Utilization is not updated into etcd when there is a change 

### ISSUE THREAD

**Issue by cybernth** [Tendrl/ceph_integration#271]
Pool/cluster Utilization is not updated into etcd when there is a change. Probably this is applicable to other parameters as well.

Workaround - Restart the ceph-integration to see the updated values

**Comment by r0h4n** [comment]
@shtripat @nthomas-redhat please test these fixes (merged in master), I couldnt finish testing because my ceph cluster went into ERR Health
