### ISSUE TITLE
Creation of RBD in non-ec pool times out

### ISSUE THREAD

**Issue by shtripat** [Tendrl/ceph_integration#286]

**Comment by shtripat** [comment]
External issue: https://bugzilla.redhat.com/show_bug.cgi?id=1455597

**Comment by r0h4n** [comment]
Whats the fix PR for this?

**Comment by shtripat** [comment]
Fix PR: https://github.com/Tendrl/ceph-integration/pull/277

**Comment by r0h4n** [comment]
@shtripat has tested creation of RBD with non-ec pool
