### ISSUE TITLE
Import Error in manager/__init__.py

### ISSUE THREAD

**Issue by rishubhjain** [Tendrl/ceph_integration#304]
https://github.com/Tendrl/ceph-integration/blob/develop/tendrl/ceph_integration/manager/__init__.py#L6 cause import error (https://travis-ci.org/Tendrl/ceph-integration/jobs/244887797#L255).
I suppose the reason of this error is recursive import calls to the manager module by sds_sync/__init__.py .

**Comment by r0h4n** [comment]
Please send PR

**Comment by rishubhjain** [comment]
@r0h4n https://github.com/Tendrl/ceph-integration/pull/305 this solves the error, but I am not sure if its one of the best solution.
