### ISSUE TITLE
Handling NoneType return in ceph_integration/ceph.py

### ISSUE THREAD

**Issue by rishubhjain** [Tendrl/ceph_integration#308]
https://github.com/Tendrl/ceph-integration/blob/develop/tendrl/ceph_integration/ceph.py#L723 might return ceph_version and empty dict, which will be followed by returning a None Type by https://github.com/Tendrl/ceph-integration/blob/develop/tendrl/ceph_integration/ceph.py#L847. I feel returning NoneType should be handled before https://github.com/Tendrl/ceph-integration/blob/develop/tendrl/ceph_integration/ceph.py#L873

**Comment by rishubhjain** [comment]
@shtripat If possible could you look into this as well. would like to discuss this.

**Comment by r0h4n** [comment]
Valid bug
