### ISSUE TITLE
Improvising RequestStateError (custom made Exception)

### ISSUE THREAD

**Issue by rishubhjain** [Tendrl/ceph_integration#309]
There is a small syntax error at https://github.com/Tendrl/ceph-integration/blob/develop/tendrl/ceph_integration/manager/exceptions.py#L4.
Also missing call to Base Class(Exception) https://github.com/Tendrl/ceph-integration/blob/develop/tendrl/ceph_integration/manager/exceptions.py#L1

**Comment by r0h4n** [comment]
Valid bug
