### ISSUE TITLE
pool creation is getting failed 

### ISSUE THREAD

**Issue by kamleshverma1** [Tendrl/ceph_integration#44]
While creating pool , after filling all appropriate fields and submit , we are getting JOB id . but internally it's not creating pool as not coming newly created pool in pool list API.
Job request data - {"Pool.poolname":"pool2","Pool.pg_num":64,"Pool.min_size":1,"Tendrl_context.sds_name":"ceph","Tendrl_context.sds_version":"1.2.3"} 

Job response data - { job_id: "xxxxxxxxxxx" }

**Comment by r0h4n** [comment]
Please provide API job and API response for that job
