### ISSUE TITLE
pool deletion is getting failed

### ISSUE THREAD

**Issue by kamleshverma1** [Tendrl/ceph_integration#45]
While deleting pool , we are getting JOB id after delete request. but internally it's not deleting pool as it is still there in pool list API.

Job request data - {"Pool.pool_id":"xxxx","Tendrl_context.sds_name":"pool1","_method":"DELETE"}

Job response data - { job_id: "xxxxxxxxxxx" }

**Comment by r0h4n** [comment]
Please provide API job and API response for that job
