### ISSUE TITLE
Ceph cluster import not finished

### ISSUE THREAD

**Issue by mkudlej** [Tendrl/ceph_integration#49]
I've tried to import Ceph cluster installed by Console 2.
I've called:
```
curl -X POST -d '{"Node[]":["dhcp-127-190", "dhcp-127-188", "dhcp-127-189", "dhcp-127-187", "dhcp-127-186", "dhcp-127-185", "dhcp-127-184"], "Tendrl_context.sds_name": "ceph", "Tendrl_context.sds_version": "10.2.3"}' mkudlej-usm5-server:9292/1.0/CephImportCluster
```
It returns cluster id.
If I list queue in Etcd I see one finished task:
```
{
  "status": "finished",
  "run": "tendrl.node_agent.ceph_integration.flows.import_cluster.ImportCluster",
  "parameters": {
    "Tendrl_context.sds_version": "10.2.3",
    "Tendrl_context.sds_name": "ceph",
    "Tendrl_context.cluster_id": "c83e6567-0c65-4056-bfab-ffc6828515e9",
    "Node[]": [
      "dhcp-127-190",
      "dhcp-127-188",
      "dhcp-127-189",
      "dhcp-127-187",
      "dhcp-127-186",
      "dhcp-127-185",
      "dhcp-127-184"
    ],
    "log": []
  },
  "created_from": "API",
  "cluster_id": "c83e6567-0c65-4056-bfab-ffc6828515e9",
  "request_id": "007807f4-e546-4d7d-8551-05815fa9e6b3/flow_6b2698fa-b665-44ad-9ae6-c6f43fe2713f",
  "type": "node"
}   
```
and one unfinished task for every node in cluster:
```
{ 
  "status": "new",
  "run": "tendrl.node_agent.ceph_integration.flows.import_cluster.ImportCluster",
  "parameters": {
    "Tendrl_context.sds_version": "10.2.3",
    "Tendrl_context.sds_name": "ceph",
    "Node[]": [
      "dhcp-127-184"
    ],
    "Tendrl_context.cluster_id": "c83e6567-0c65-4056-bfab-ffc6828515e9",
    "log": []
  },
  "parent": "007807f4-e546-4d7d-8551-05815fa9e6b3/flow_6b2698fa-b665-44ad-9ae6-c6f43fe2713f",
  "node_id": "dhcp-127-184",
  "cluster_id": "c83e6567-0c65-4056-bfab-ffc6828515e9",
  "type": "node"
}   
```

It seems that cluster is no imported because 
```
culr mkudlej-usm5-server.usmqe:9292/1.0/c83e6567-0c65-4056-bfab-ffc6828515e9/Flows
```
doesn't return anything.

I see this traceback on nodes in tendrl/node_agent/error log:
```
2016-12-02T14:22:21+0000 - rpc.py:160 -                 _run() - ERROR - Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/tendrl/node_agent/manager/rpc.py", line 158, in _run
    self._server.run()
  File "/usr/lib/python2.7/site-packages/tendrl/node_agent/manager/rpc.py", line 81, in run
    self._acceptor()
  File "/usr/lib/python2.7/site-packages/tendrl/node_agent/manager/rpc.py", line 59, in _acceptor
    jobs = self.client.read("/queue")
  File "/usr/lib/python2.7/site-packages/etcd/client.py", line 562, in read
    timeout=timeout)
  File "/usr/lib/python2.7/site-packages/etcd/client.py", line 874, in wrapper
    return self._handle_server_response(response)
  File "/usr/lib/python2.7/site-packages/etcd/client.py", line 954, in _handle_server_response
    etcd.EtcdError.handle(r)
  File "/usr/lib/python2.7/site-packages/etcd/__init__.py", line 304, in handle
    raise exc(msg, payload)
EtcdKeyNotFound: Key not found : /queue
```

I've used these packages:
server:
etcd-2.3.7-4.el7.x86_64
rubygem-etcd-0.3.0-1.el7.centos.noarch
tendrl-api-0.0.1-1.el7.centos.noarch
tendrl-api-doc-0.0.1-1.el7.centos.noarch
tendrl-api-httpd-0.0.1-1.el7.centos.noarch

nodes:
ceph-base-10.2.3-13.el7cp.x86_64
ceph-common-10.2.3-13.el7cp.x86_64
ceph-osd-10.2.3-13.el7cp.x86_64
ceph-selinux-10.2.3-13.el7cp.x86_64
libcephfs1-10.2.3-13.el7cp.x86_64
python-cephfs-10.2.3-13.el7cp.x86_64
python-etcd-0.4.3-1.noarch
tendrl-ceph-integration-0.0.1-1.el7.centos.noarch
tendrl-common-0.0.1-1.el7.centos.noarch
tendrl-node-agent-0.0.1-1.el7.centos.noarch

**Comment by r0h4n** [comment]
Hi, Please provide Tendrl logs for all nodes in the cluster 
      "dhcp-127-190",
      "dhcp-127-188",
      "dhcp-127-189",
      "dhcp-127-187",
      "dhcp-127-186",
      "dhcp-127-185",
      "dhcp-127-184"

**Comment by mkudlej** [comment]
Here are log from all machines:
[dhcp-127-184.tar.gz](https://github.com/Tendrl/ceph_integration/files/631055/dhcp-127-184.tar.gz)
[dhcp-127-185.tar.gz](https://github.com/Tendrl/ceph_integration/files/631060/dhcp-127-185.tar.gz)
[dhcp-127-186.tar.gz](https://github.com/Tendrl/ceph_integration/files/631056/dhcp-127-186.tar.gz)
[dhcp-127-187.tar.gz](https://github.com/Tendrl/ceph_integration/files/631061/dhcp-127-187.tar.gz)
[dhcp-127-188.tar.gz](https://github.com/Tendrl/ceph_integration/files/631058/dhcp-127-188.tar.gz)
[dhcp-127-189.tar.gz](https://github.com/Tendrl/ceph_integration/files/631057/dhcp-127-189.tar.gz)
[dhcp-127-190.tar.gz](https://github.com/Tendrl/ceph_integration/files/631059/dhcp-127-190.tar.gz)

**Comment by r0h4n** [comment]
Thanks for the logs, I managed to reproduce this one, will update when patch is ready

**Comment by r0h4n** [comment]
Fixed: https://github.com/Tendrl/node_agent/pull/85
