### ISSUE TITLE
check_commit_msg.py displays a misleading error message

### ISSUE THREAD

**Issue by anmolbabu** [Tendrl/ceph_integration#53]
The check_commit_msg.py complains that the commis message should be of the form :

'tendrl-bug-id:<tendrl_repo>/issue_id'

It should probably say :

tendrl-bug-id:Tendrl/<tendrl_repo_name>#<issue_id>

**Comment by GowthamShanmugam** [comment]
@anmolbabu Tendrl-bug-id : should be <tendrl_repo>/#issue_id, Then only a commit will be updated in issue page

**Comment by anmolbabu** [comment]
@GowthamShanmugam  Please follow the commit message as in: https://github.com/Tendrl/common/pull/64 and I raised this isssue in accordance with that

**Comment by GowthamShanmugam** [comment]
@anmolbabu i will change message as per your comment
