### ISSUE TITLE
ceph_integration service should read cluster-id from config file.

### ISSUE THREAD

**Issue by nnDarshan** [Tendrl/ceph_integration#56]
ceph-integration service should read the cluster-id from the conf file instead of expecting a command line argument.

**Comment by r0h4n** [comment]
Is this related to any spec?

**Comment by nnDarshan** [comment]
@r0h4n Feel this is a bug, is a spec needed ?

**Comment by r0h4n** [comment]
Hmm.. ok, send in a fix
