### ISSUE TITLE
tendrl-ceph-integration can't be shipped with default configuration

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/ceph_integration#57]
It's not directly possible to ship `tendrl-ceph-integration` component with configuration file(s) which would contain all default values known in advance (eg. before installation).

Eg. we know that we need to set this piece of configuration into `/etc/tendrl/tendrl.conf` (see [installation.rst](https://github.com/Tendrl/ceph_integration/blob/master/doc/source/installation.rst)):

```
[ceph_integration]
log_cfg_path = /etc/tendrl/ceph_integration_logging.yaml
```

But it's not possible to ship this in a default configuration file in binary package, because `tendrl.conf` configuration file is owned by `tendrl-node-agent` component.

**Comment by mbukatov** [comment]
I created issue for https://github.com/Tendrl/node_agent/issues/99 as well - since this component [happens to own](https://github.com/Tendrl/common/issues/74#issuecomment-265350087) the `tendrl.conf`.

**Comment by mbukatov** [comment]
This issue is of the same kind as https://github.com/Tendrl/gluster_integration/issues/86

**Comment by TimothyAsirJeyasing** [comment]
Spec created to resolve this kind of issues https://github.com/Tendrl/specifications/issues/68 which is under review
