### ISSUE TITLE
Re-factor ceph integration code to extend/use common module

### ISSUE THREAD

**Issue by shtripat** [Tendrl/ceph_integration#59]
The common module provides all the base classes for flows, atoms, manager, job queue handler, persister and contains all the utilities which are generic in nature like exceptions, command executor, service manager and package installer. The cep_integration modules should extend/use these common module changes.

**Comment by r0h4n** [comment]
Any updates? Add Spec issue here please

**Comment by shtripat** [comment]
Linked to spec issue https://github.com/Tendrl/specifications/issues/31

Will start code changes tomorrow :)

**Comment by shtripat** [comment]
Re-factoring PRs got merged upstream
